eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://user1:pass1234@localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: item-service
  security:
    user:
      name: user1
      password: pass1234
  boot:
    admin:
      client:
        url: http://admin:admin@localhost:8888/
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'